networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.33.0/24

services:
  poisoning: 
    image: poisoning
    deploy:
      resources:
        limits:
          cpus: 2.0
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mqtt
    volumes:
      - ./database:/home/app/database
    networks:
      - my_network

  clustering:
    image: clustering
    deploy:
      resources:
        limits:
          cpus: 16.0
    shm_size: '512m'
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mqtt
    volumes:
      - ./database:/home/app/database
    networks:
      - my_network

  training:
    image: training
    deploy:
      resources:
        limits:
          cpus: 16.0
    shm_size: '512m'
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mqtt
    volumes:
      - ./database:/home/app/database
    networks:
      - my_network

  monitoring:
    image: monitoring
    deploy:
      resources:
        limits:
          cpus: 0.50
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mqtt
    volumes:
      - ./database:/home/app/database
    networks:
      - my_network

  controller:
    image: controller
    deploy:
      resources:
        limits:
          cpus: 0.50
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mqtt
    networks:
      - my_network

  mosquitto:
    container_name: mqtt
    deploy:
      resources:
        limits:
          cpus: 1.0
    expose:
      - "1883"
    ports:
      - "1883:1883"
    restart: unless-stopped
    image: toke/mosquitto
    networks:
      - my_network

  scaphandre:
    image: hubblo/scaphandre
    deploy:
      resources:
        limits:
          cpus: 1.0
    privileged: true
    ports: 
      - "8080:8080"
    volumes:
      - type: bind
        source: /proc
        target: /proc
      - type: bind
        source: /sys/class/powercap
        target: /sys/class/powercap
    command: ["prometheus"]                         
    networks:
      - my_network

  prometheus:
    build:
      context: ./prometheus
    deploy:
      resources:
        limits:
          cpus: 1.0
    ports: 
      - "9090:9090"
    volumes: 
      - promdata-scaphandre:/prometheus 
    networks:
      - my_network

  grafana:
    image: grafana/grafana:10.4.12
    deploy:
      resources:
        limits:
          cpus: 1.0
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"
      # GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/sample/sample-dashboard.json"
    depends_on:
      - prometheus
    ports: 
      - "3000:3000"
    networks:
      - my_network

volumes:
  promdata-scaphandre:
