{
 "title": "Inference Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Overall Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "inference_accuracy{poison=\"False\"} * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "inference_accuracy{cluster=\"False\", poison=\"True\"} * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "inference_accuracy{cluster=\"True\", poison=\"True\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source Class Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "inference_source_accuracy{poison=\"False\"} * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "inference_source_accuracy{cluster=\"False\", poison=\"True\"} * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "inference_source_accuracy{cluster=\"True\", poison=\"True\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targeted Missclassification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "inference_target_missclass{poison=\"False\"} * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "inference_target_missclass{cluster=\"False\", poison=\"True\"} * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "inference_target_missclass{cluster=\"True\", poison=\"True\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}