FROM mcr.microsoft.com/devcontainers/python:1-3.8-bullseye

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     libedit-dev  \
#     llvm \
#     llvm-dev

# RUN LLVM_CONFIG=/usr/bin/llvm-config-11